In [77]:
import pandas as pd
import math

In [78]:
# Abre o arquivo utilizado anteriormente, que possui os dados da 
# Pesquisa Destino 2017 com as colunas tratadas + os fatores de 
# crescimento populacional do IBGE
file_path = 'OD_2017_E_IBGE.csv'
df = pd.read_csv(file_path, low_memory=False)
print(df.columns)
df.head()

Index(['ZONA - Zona do Domicílio', 'MUNI_DOM - Município de Domicílio',
       'CO_DOM_X - Coordenada X Domicílio',
       'CO_DOM_Y - Coordenada Y Domicílio', 'ID_DOM - Identifica Domicílio',
       'F_DOM - Identifica Primeiro Registro do Domicílio',
       'FE_DOM - Fator de Expansão do Domicílio', 'DOM - Número do Domicílio',
       'CD_ENTRE - Código de Entrevista', 'DATA - Data da Entrevista',
       ...
       'FE_PESS_2055', 'FE_PESS_2060', 'FE_VIA_2023', 'FE_VIA_2025',
       'FE_VIA_2035', 'FE_VIA_2040', 'FE_VIA_2045', 'FE_VIA_2050',
       'FE_VIA_2055', 'FE_VIA_2060'],
      dtype='object', length=260)

,ZONA - Zona do Domicílio,MUNI_DOM - Município de Domicílio,CO_DOM_X - Coordenada X Domicílio,CO_DOM_Y - Coordenada Y Domicílio,ID_DOM - Identifica Domicílio,F_DOM - Identifica Primeiro Registro do Domicílio,FE_DOM - Fator de Expansão do Domicílio,DOM - Número do Domicílio,CD_ENTRE - Código de Entrevista,DATA - Data da Entrevista,...,FE_PESS_2055,FE_PESS_2060,FE_VIA_2023,FE_VIA_2025,FE_VIA_2035,FE_VIA_2040,FE_VIA_2045,FE_VIA_2050,FE_VIA_2055,FE_VIA_2060
0,1,36,333743,7394463,10001,1,15.42,1,1,6092017,...,26.32,24.39,24.44,25.04,29.80,32.19,31.79,29.63,29.82,27.64
1,1,36,333743,7394463,10001,0,15.42,1,1,6092017,...,NaN,NaN,24.44,25.04,29.80,32.19,31.79,29.63,29.82,27.64
2,1,36,333743,7394463,10001,0,15.42,1,1,6092017,...,13.45,13.06,18.24,17.62,17.11,17.09,16.54,15.82,15.25,14.80
3,1,36,333743,7394463,10001,0,15.42,1,1,6092017,...,NaN,NaN,18.24,17.62,17.11,17.09,16.54,15.82,15.25,14.80
4,1,36,333743,7394463,10001,0,15.42,1,1,6092017,...,NaN,NaN,18.24,17.62,17.11,17.09,16.54,15.82,15.25,14.80

In [79]:
# adiciona uma coluna para identificar o tipo de veículo, de acordo com o modal 
# principal utilizado, esse indicador irá informar se é um veículo leve, moto ou pesado:
# 0: Não se aplica, 1: Moto, 2: Leve, 3: Pesado
tipos = {
    1: 0, #'Metrô',
    2: 0, #'Trem',
    3: 0, #'Monotrilho',
    4: 3, #'Ônibus/micro-ônibus/perua do município de São Paulo',
    5: 3, #'Ônibus/micro-ônibus/perua de outros municípios',
    6: 3, #'Ônibus/micro-ônibus/perua metropolitano',
    7: 3, #'Transporte Fretado',
    8: 3, #'Transporte Escolar',
    9: 2, #'Dirigindo Automóvel',
    10: 0, #'Passageiro de Automóvel',
    11: 2, #'Táxi Convencional',
    12: 2, #'Táxi não Convencional',
    13: 1, #'Dirigindo Moto',
    14: 0, #'Passageiro de Moto',
    15: 0, #'Bicicleta',
    16: 0, #'A Pé',
    17: 3, #'Outros'
}
df['tipo_veiculo'] = df['MODOPRIN - Modo Principal'].map(tipos)
df.tail()

,ZONA - Zona do Domicílio,MUNI_DOM - Município de Domicílio,CO_DOM_X - Coordenada X Domicílio,CO_DOM_Y - Coordenada Y Domicílio,ID_DOM - Identifica Domicílio,F_DOM - Identifica Primeiro Registro do Domicílio,FE_DOM - Fator de Expansão do Domicílio,DOM - Número do Domicílio,CD_ENTRE - Código de Entrevista,DATA - Data da Entrevista,...,FE_PESS_2060,FE_VIA_2023,FE_VIA_2025,FE_VIA_2035,FE_VIA_2040,FE_VIA_2045,FE_VIA_2050,FE_VIA_2055,FE_VIA_2060,tipo_veiculo
183087,517,25,294618,7410518,5171418,0,85.53,1418,1,15092018,...,NaN,88.16,89.66,86.57,82.71,79.60,77.22,75.38,73.76,0.00
183088,517,25,295243,7411456,5171599,1,52.50,1599,1,15092018,...,40.77,57.58,56.69,52.98,49.07,46.58,47.70,47.65,46.19,0.00
183089,517,25,295243,7411456,5171599,0,52.50,1599,1,15092018,...,NaN,57.58,56.69,52.98,49.07,46.58,47.70,47.65,46.19,0.00
183090,517,25,295243,7411456,5171599,0,52.50,1599,1,15092018,...,40.77,57.58,56.69,52.98,49.07,46.58,47.70,47.65,46.19,0.00
183091,517,25,295243,7411456,5171599,0,52.50,1599,1,15092018,...,NaN,57.58,56.69,52.98,49.07,46.58,47.70,47.65,46.19,0.00

In [80]:
# cria uma coluna com a distância percorrida em kilômetros
df['distancia_km'] = df['DISTANCIA - Distância em metros*']/1000

# cria uma coluna com a duração da viagem em horas
df['duracao_viagem_horas'] = df['DURACAO - Duração da Viagem (em minutos)']/60

# criação de uma coluna com a velocidade em KM/H
df['velocidade_km_h'] = df['distancia_km']/df['duracao_viagem_horas']
df.head()

,ZONA - Zona do Domicílio,MUNI_DOM - Município de Domicílio,CO_DOM_X - Coordenada X Domicílio,CO_DOM_Y - Coordenada Y Domicílio,ID_DOM - Identifica Domicílio,F_DOM - Identifica Primeiro Registro do Domicílio,FE_DOM - Fator de Expansão do Domicílio,DOM - Número do Domicílio,CD_ENTRE - Código de Entrevista,DATA - Data da Entrevista,...,FE_VIA_2035,FE_VIA_2040,FE_VIA_2045,FE_VIA_2050,FE_VIA_2055,FE_VIA_2060,tipo_veiculo,distancia_km,duracao_viagem_horas,velocidade_km_h
0,1,36,333743,7394463,10001,1,15.42,1,1,6092017,...,29.80,32.19,31.79,29.63,29.82,27.64,0.00,0.64,0.17,3.83
1,1,36,333743,7394463,10001,0,15.42,1,1,6092017,...,29.80,32.19,31.79,29.63,29.82,27.64,0.00,0.64,0.17,3.83
2,1,36,333743,7394463,10001,0,15.42,1,1,6092017,...,17.11,17.09,16.54,15.82,15.25,14.80,0.00,6.65,0.83,7.98
3,1,36,333743,7394463,10001,0,15.42,1,1,6092017,...,17.11,17.09,16.54,15.82,15.25,14.80,0.00,4.24,1.00,4.24
4,1,36,333743,7394463,10001,0,15.42,1,1,6092017,...,17.11,17.09,16.54,15.82,15.25,14.80,2.00,4.56,0.67,6.84

In [81]:
def calcula_fator_emissao_co2(row):
    tipo_veiculo = row['tipo_veiculo']
    velocidade_km_h = row['velocidade_km_h']
    distancia_km = row['distancia_km']
    fator_emissao = 0
    constante = 8888.2
    if tipo_veiculo == 1:
        fator_emissao = ((constante * pow(velocidade_km_h, -0.986)) * ((distancia_km/1000)/1000000))/2
    if tipo_veiculo == 2:
        fator_emissao = (constante * pow(velocidade_km_h, -0.986)) * ((distancia_km/1000)/1000000)
    if tipo_veiculo == 3:
        constante = 4067.2
        fator_emissao = (constante * pow(velocidade_km_h, -0.396)) * ((distancia_km/1000)/1000000)

    return fator_emissao


def calcula_fator_emissao_material_particulado(row):
    tipo_veiculo = row['tipo_veiculo']
    velocidade_km_h = row['velocidade_km_h']
    distancia_km = row['distancia_km']
    fator_emissao = 0
    constante = 0.08
    if tipo_veiculo == 1:
        fator_emissao = (constante * ((distancia_km/1000)/1000000))/2
    if tipo_veiculo == 2:
        fator_emissao = (constante * ((distancia_km/1000)/1000000))
    if tipo_veiculo == 3:
        ln_velocidade = math.log(velocidade_km_h)
        constante = (1.7359 - 0.3186 * ln_velocidade)
        fator_emissao = (constante * ((distancia_km/1000)/1000000))

    return fator_emissao

In [82]:
df['co2_total'] = df.apply(lambda row: calcula_fator_emissao_co2(row), axis=1)
df['mp_total'] = df.apply(lambda row: calcula_fator_emissao_material_particulado(row), axis=1)
df.head()

,ZONA - Zona do Domicílio,MUNI_DOM - Município de Domicílio,CO_DOM_X - Coordenada X Domicílio,CO_DOM_Y - Coordenada Y Domicílio,ID_DOM - Identifica Domicílio,F_DOM - Identifica Primeiro Registro do Domicílio,FE_DOM - Fator de Expansão do Domicílio,DOM - Número do Domicílio,CD_ENTRE - Código de Entrevista,DATA - Data da Entrevista,...,FE_VIA_2045,FE_VIA_2050,FE_VIA_2055,FE_VIA_2060,tipo_veiculo,distancia_km,duracao_viagem_horas,velocidade_km_h,co2_total,mp_total
0,1,36,333743,7394463,10001,1,15.42,1,1,6092017,...,31.79,29.63,29.82,27.64,0.00,0.64,0.17,3.83,0.00,0.00
1,1,36,333743,7394463,10001,0,15.42,1,1,6092017,...,31.79,29.63,29.82,27.64,0.00,0.64,0.17,3.83,0.00,0.00
2,1,36,333743,7394463,10001,0,15.42,1,1,6092017,...,16.54,15.82,15.25,14.80,0.00,6.65,0.83,7.98,0.00,0.00
3,1,36,333743,7394463,10001,0,15.42,1,1,6092017,...,16.54,15.82,15.25,14.80,0.00,4.24,1.00,4.24,0.00,0.00
4,1,36,333743,7394463,10001,0,15.42,1,1,6092017,...,16.54,15.82,15.25,14.80,2.00,4.56,0.67,6.84,0.00,0.00

In [83]:
file_path = 'OD_2017_E_IBGE_E_ANTP_IPEA.csv'
df.to_csv(file_path)
print('Arquivo de saída salvo com sucesso.')

Arquivo de saída salvo com sucesso.

In [84]:
df.columns

Index(['ZONA - Zona do Domicílio', 'MUNI_DOM - Município de Domicílio',
       'CO_DOM_X - Coordenada X Domicílio',
       'CO_DOM_Y - Coordenada Y Domicílio', 'ID_DOM - Identifica Domicílio',
       'F_DOM - Identifica Primeiro Registro do Domicílio',
       'FE_DOM - Fator de Expansão do Domicílio', 'DOM - Número do Domicílio',
       'CD_ENTRE - Código de Entrevista', 'DATA - Data da Entrevista',
       ...
       'FE_VIA_2045', 'FE_VIA_2050', 'FE_VIA_2055', 'FE_VIA_2060',
       'tipo_veiculo', 'distancia_km', 'duracao_viagem_horas',
       'velocidade_km_h', 'co2_total', 'mp_total'],
      dtype='object', length=266)